//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace EmployeeCRUD_MDG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Full Name is Required")]
        public string FullName { get; set; }
        [Required]
        public string Position { get; set; }
        [Required]
        public string Department { get; set; }
        [Range(1000, 100000, ErrorMessage = "Salary Must be between 1000 or 100000")]
        public Nullable<decimal> Salary { get; set; }
    }
}
